language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test
    - stage: semantic release
      script: npm run semantic-release
stages:
  - name: test
  - name: semantic release
    if: branch = master
branches:
  except:
    # ignore version tag branches from semantic release
    - /^v\d+\.\d+\.\d+$/
